function contract = contact_consistent_differential_contract()
%CONTACT_CONSISTENT_DIFFERENTIAL_CONTRACT Frozen Phase-5 G1 design contract.
% This file records inspection-backed contact observability and metadata rules.
% Candidate-model fields are appended by the G1 model-contract task.

contract = struct();
contract.contractVersion = "05-01-G1";
contract.convention = "(right-left)/2";
contract.contactObservability = contactObservability();
contract.metadataRules = metadataRules();
contract.stateCore = ["xiDelta", "dxiDelta", "vRollDelta"];
contract.inputContract = realizableInputContract();
contract.candidateInterface = candidateInterface( ...
    contract.stateCore, contract.contactObservability);
contract.modelLadder = modelLadder();
contract.rejectedSubstitutions = [ ...
    "abstractSlowContactState", "independentForceAndTorqueInputs", ...
    "higherOrderArx", "broadHistoryTerms", "neuralSubstitute"];
contract.validationGates = validationGates();
contract.executionBoundary = executionBoundary();
contract.approvalRule = ...
    "No NMPC integration readiness claim until multi-step, free-run, held-seed, and held-yaw gates pass without relaxed limits.";
contract.escalationConditions = [ ...
    "Frozen convention or three-state core must change", ...
    "Audited input basis or WBC architecture must change", ...
    "Plant parameters, controller limits, or validation thresholds must change", ...
    "Implementation requires more than smoke execution"];
contract.scopeFences = [ ...
    "No NMPC prediction-dynamics replacement in this phase", ...
    "No WBC objective, constraint, friction, torque, or bound redesign", ...
    "No plant-parameter change", ...
    "No large-yaw acceptance, terrain/contact switching, or hardware claim"];
end

function input = realizableInputContract()
persistent cachedAudit
if isempty(cachedAudit)
    cachedAudit = audit_differential_realizable_input_basis();
end
audit = cachedAudit;
input = struct();
input.name = audit.name;
input.rank = audit.rank;
input.basis = audit.basis;
input.targetPairBasis = audit.targetPairBasis;
input.taskProjection = audit.taskProjection;
input.nullspaceDimension = audit.nullspaceDimension;
input.nullspaceBasis = audit.nullspaceBasis;
input.coupledWrenchImage = audit.coupledWrenchImage;
input.limits = audit.limits;
input.frames = audit.frames;
input.unit = audit.inputUnit;
input.convention = audit.convention;
input.realizedInputRequired = true;
input.commandToRealizedDiagnosticsRequired = true;
input.auditArtifactPath = audit.artifactPath;
end

function interface = candidateInterface(stateCore, observability)
directNames = string({observability.availableDirect.name});
interface = struct();
interface.signature = ...
    "xDotDiff=f(xDiffCore,uDiffRealizable,contactState,configuration)";
interface.stateArgument = "xDiffCore";
interface.stateOrder = stateCore;
interface.inputArgument = "uDiffRealizable";
interface.inputDimension = 1;
interface.contactArgument = "contactState";
interface.contactStateOrder = directNames;
interface.contactStatePolicy = ...
    "Use only inspection-confirmed direct physical outputs; current order is empty and proxies are forbidden.";
interface.configurationArgument = "configuration";
interface.configurationFields = ["forwardSpeed", "yawRate"];
interface.output = "xDotDiff";
interface.outputOrder = stateCore;
interface.onlineEvaluable = true;
interface.interpretable = true;
interface.stateJacobian = "df/dxDiffCore [3x3]";
interface.inputJacobian = "df/duDiffRealizable [3x1]";
interface.contactJacobian = "df/dcontactState [3xnContact]";
interface.configurationJacobian = "df/dconfiguration [3xnConfiguration]";
interface.linearizationA = "stateJacobian";
interface.linearizationB = "inputJacobian";
interface.linearizationContact = "contactJacobian";
interface.linearizationConfiguration = "configurationJacobian";
interface.evaluationOutputs = [ ...
    "xDotDiff", "stateJacobian", "inputJacobian", ...
    "contactJacobian", "configurationJacobian"];
end

function ladder = modelLadder()
ladder = [
    modelStep(1, "physicalOrAlgebraicContactModel", ...
        "preferred", "Use the frozen state, realized input, and direct contact state."), ...
    modelStep(2, "lowOrderNonlinearModel", ...
        "allowed-after-evidence", ...
        "Use only if the physical/algebraic form cannot pass the frozen gates."), ...
    modelStep(3, "stateDependentParameterization", ...
        "conditional", ...
        "Use only when residual and held-out evidence identifies the dependency.")];
end

function step = modelStep(priority, modelClass, disposition, condition)
step = struct("priority", priority, "modelClass", modelClass, ...
    "disposition", disposition, "condition", condition);
end

function gates = validationGates()
gates = [
    gate("signedExcitation", ...
        "Positive and negative realizable input; coupled realized wrench and command-to-realized diagnostics."), ...
    gate("preBoundaryAndFullWindow", ...
        "Report both pre-boundary and complete-window metrics with unchanged cutoffs."), ...
    gate("heldSeed", ...
        "Leave-one-seed validation using the retained Model-C infrastructure."), ...
    gate("heldYaw", ...
        "Leave-one-yaw validation using the retained Model-C infrastructure."), ...
    gate("multiStep", ...
        "One-second and configured multi-step prediction metrics."), ...
    gate("freeRun", ...
        "Complete free-run R-squared, RMSE, bias, and boundedness evidence."), ...
    gate("residualCorrelation", ...
        "Residual correlation against state, realized input, direct contact, and configuration fields."), ...
    gate("residualPsd", ...
        "Residual PSD including an explicit check near 1.9 Hz before any order increase."), ...
    gate("mirror", ...
        "Positive/negative and left/right mirror behavior under (right-left)/2."), ...
    gate("torquePath", ...
        "Retained torque-path diagnostics with unchanged torque limits.")];
end

function item = gate(name, evidence)
item = struct("name", name, "required", true, ...
    "thresholdPolicy", "reuse-existing-unrelaxed", "evidence", evidence);
end

function boundary = executionBoundary()
boundary = struct();
boundary.agentRuns = "smoke-only";
boundary.manualFullBatchCaseCount = 25;
boundary.manualFullBatchMode = "full";
boundary.requiredFilters = ["YawRate", "Seed"];
boundary.requiredResumability = [ ...
    "skip-completed", "independent-case-save", "failure-continuation", ...
    "summary", "manifest", "metadata"];
boundary.expectedEntryPoint = ...
    "run_contact_consistent_differential_validation_batch";
boundary.fullBatchOwner = "human-manual-gate";
end

function observability = contactObservability()
contactName = "Spatial" + newline + "Contact Force";
contactName1 = "Spatial" + newline + "Contact Force1";
observability = struct();
observability.inspectionMethod = ...
    "MATLAB load_system/find_system/get_param inspection of current SLX files";
observability.inspectedModels = [
    struct("model", "source.slx", ...
        "subsystem", "source/PD_only", ...
        "contactBlocks", ["source/PD_only/" + contactName, ...
            "source/PD_only/" + contactName1], ...
        "contactBlockCount", 2, ...
        "transformSensorCount", 0), ...
    struct("model", "source_common.slx", ...
        "subsystem", "source_common/PD_only", ...
        "contactBlocks", "source_common/PD_only/" + contactName1, ...
        "contactBlockCount", 1, ...
        "transformSensorCount", 0)];
observability.inspectionEvidence = struct( ...
    "contactBlockType", "Simscape Multibody Spatial Contact Force", ...
    "normalModel", "SmoothSpringDamper", ...
    "frictionModel", "SmoothStickSlip", ...
    "simulinkSignalInputCount", 0, ...
    "simulinkSignalOutputCount", 0, ...
    "conservingPortCount", 2, ...
    "normalForceSensing", "off", ...
    "frictionForceSensing", "off", ...
    "transformSensorCount", 0);

observability.availableDirect = emptyDirectSignal();
inspectedContactLocations = [
    "source/PD_only/" + contactName, ...
    "source/PD_only/" + contactName1, ...
    "source_common/PD_only/" + contactName1];
noSignalLimitation = "Contact physics exists, but the inspected blocks have " + ...
    "no enabled Simulink/physical-signal output for this quantity.";
observability.unavailableDirect = [
    unavailable("perWheelPenetration", "m", inspectedContactLocations, ...
        noSignalLimitation), ...
    unavailable("perWheelNormalCompression", "m", ...
        inspectedContactLocations, noSignalLimitation), ...
    unavailable("perWheelRollingSlip", "m/s", ...
        inspectedContactLocations, noSignalLimitation), ...
    unavailable("perWheelRelativeContactVelocity", "m/s", ...
        inspectedContactLocations, noSignalLimitation), ...
    unavailable("perWheelNormalForce", "N", ...
        inspectedContactLocations, ...
        "Normal-force sensing is explicitly off in every inspected contact block."), ...
    unavailable("perWheelFrictionForce", "N", ...
        inspectedContactLocations, ...
        "Friction-force sensing is explicitly off in every inspected contact block.")];

observability.excludedProxies = [
    proxy("normalLoadDifference", ...
        "spatial_two_leg_qp_core/debug.contactForceDifferential", ...
        "analytic WBC contact-force solution, not Simscape contact deformation"), ...
    proxy("filteredOrRealizedInput", ...
        "spatial_two_leg_qp_core/debug.wrenchFeasible", ...
        "controller-side realized wrench, not a physical contact state"), ...
    proxy("rollingConfigurationResidual", ...
        "spatial_two_leg_qp_core/debug.xiDifferential", ...
        "wheel configuration difference, not contact penetration or compression"), ...
    proxy("contactAccelerationResidual", ...
        "spatial_two_leg_qp_core/debug.contactResidual", ...
        "analytic WBC acceleration residual, not a measured Simscape contact output")];
end

function rules = metadataRules()
rules = struct();
rules.requiredForEveryAvailableDirectQuantity = [ ...
    "sourcePath", "unit", "sign", "sampleTime", "convention"];
rules.sourceRule = ...
    "Use the exact producing model/block and output port; do not infer a source.";
rules.unitRule = "Record the physical unit declared by the producing block.";
rules.signRule = ...
    "Record positive physical direction before forming a differential signal.";
rules.sampleTimeRule = ...
    "Record the actual producer/logging sample time; do not substitute NMPC rate.";
rules.leftRightRule = ...
    "Store left and right channels separately and derive differential as (right-left)/2.";
rules.proxyRule = ...
    "Controller force, input, configuration, and residual signals remain proxies and may not be relabeled as contact deformation.";
rules.unavailableRule = ...
    "Record inspected model locations and the precise missing or disabled output.";
end

function item = emptyDirectSignal()
item = struct("name", {}, "sourcePath", {}, "unit", {}, ...
    "sign", {}, "sampleTime", {}, "convention", {});
end

function item = unavailable(name, expectedUnit, inspectedLocation, limitation)
item = struct("name", name, "availability", "unavailable", ...
    "expectedUnit", expectedUnit, ...
    "inspectedLocation", inspectedLocation, ...
    "limitation", limitation);
end

function item = proxy(name, sourcePath, reason)
item = struct("name", name, "classification", "proxy", ...
    "sourcePath", sourcePath, "reason", reason, ...
    "mayLabelAsContactDeformation", false);
end
