function manifest = contact_ground_truth_manifest()
%CONTACT_GROUND_TRUTH_MANIFEST Frozen Phase-6 contact observation contract.
% The manifest is a decision artifact.  It describes sensing outputs that
% may be exposed by G2, but it does not modify or save source.slx.

rightBlock = "source/PD_only/Spatial" + newline + "Contact Force";
leftBlock = "source/PD_only/Spatial" + newline + "Contact Force1";

manifest = struct();
manifest.schemaVersion = "contact-ground-truth/1.0.0";
manifest.status = "ready_for_g2";
manifest.canonicalConvention = canonicalConvention();
manifest.legacyMapping = legacyMapping(manifest.schemaVersion);
manifest.sourceClasses = sourceClasses();
manifest.selectedSignals = selectedSignals(leftBlock, rightBlock);
manifest.unavailableSignals = unavailableSignals(leftBlock, rightBlock);
manifest.proxySignals = proxySignals();
manifest.loggingContract = observationLoggingContract(manifest.selectedSignals);
manifest.scopeFences = scopeFences();
manifest.escalation = escalation();
manifest.inspection = inspectionEvidence(leftBlock, rightBlock);
end

function convention = canonicalConvention()
convention = struct( ...
    "schema", "phase-6-canonical-v1", ...
    "differential", "(right-left)/2", ...
    "commonMode", "(right+left)/2", ...
    "appliesTo", ["new contact quantities", "xiDeltaCanonical", ...
        "dxiDeltaCanonical", "vRollDelta", "uDiffRealizable"], ...
    "rawSidePolicy", "retain left and right channels before deriving pairs", ...
    "canonicalStateFields", ["xiDeltaCanonical", ...
        "dxiDeltaCanonical", "vRollDelta"], ...
    "legacyStateFields", ["xiDeltaLegacy", "dxiDeltaLegacy"], ...
    "pairDerivationPolicy", ...
        "derive canonical/common fields only after left/right timestamp alignment");
end

function mapping = legacyMapping(targetSchema)
mapping = struct( ...
    "sourceSchema", "differential-identification/legacy-v1", ...
    "targetSchema", targetSchema, ...
    "fields", ["xiDelta", "dxiDelta"], ...
    "legacyConvention", "(left-right)/2", ...
    "canonicalConvention", "(right-left)/2", ...
    "conversion", "canonical=-legacy", ...
    "scale", -1, ...
    "rewritePolicy", "never overwrite legacy processed evidence", ...
    "provenanceRequired", true);
end

function classes = sourceClasses()
classes = [ ...
    sourceClass("plant_ground_truth", ...
        "Quantity measured by an output of the Simscape contact block.", true), ...
    sourceClass("controller_proxy", ...
        "Controller/WBC command, solution, or diagnostic; not contact ground truth.", false), ...
    sourceClass("derived_kinematic_proxy", ...
        "Quantity derived from body, joint, or wheel kinematics; not contact ground truth.", false)];
end

function item = sourceClass(name, definition, mayBeGroundTruth)
item = struct("name", name, "definition", definition, ...
    "mayBeGroundTruth", mayBeGroundTruth);
end

function signals = selectedSignals(leftBlock, rightBlock)
signals = repmat(emptySelected(), 0, 1);
for side = ["left", "right"]
    if side == "left"
        block = leftBlock;
        ownership = "Cylindrical Solid1 -> Revolute Joint5 -> configured left chain";
    else
        block = rightBlock;
        ownership = "Cylindrical Solid -> Revolute Joint2 -> configured right chain";
    end
    suffix = upper(extractBefore(side, 2)) + extractAfter(side, 1);
    signals(end + 1) = selected("contactStatus" + suffix, side, block, ...
        "con", "SenseContactSignal", ...
        "Scalar contact status for the geometry pair.", "1", ...
        "frame independent scalar", ...
        "1 means contact; 0 means separated", "scalar", ownership); %#ok<AGROW>
    signals(end + 1) = selected("contactPenetration" + suffix, side, block, ...
        "pen", "SensePenetrationDepth", ...
        "Geometric penetration depth between the two contact geometries.", "m", ...
        "frame independent scalar distance", ...
        "positive overlap; zero when not penetrating", "scalar", ownership); %#ok<AGROW>
    signals(end + 1) = selected("contactNormalForceMagnitude" + suffix, side, block, ...
        "fnm", "SenseNormalForceMagnitude", ...
        "Magnitude of the normal force between the contact geometries.", "N", ...
        "frame independent magnitude", ...
        "nonnegative magnitude; no direction sign", "scalar", ownership); %#ok<AGROW>
    signals(end + 1) = selected("contactFrictionForceMagnitude" + suffix, side, block, ...
        "ffrm", "SenseFrictionalForceMagnitude", ...
        "Magnitude of the frictional force between the contact geometries.", "N", ...
        "frame independent magnitude", ...
        "nonnegative magnitude; no direction sign", "scalar", ownership); %#ok<AGROW>
    signals(end + 1) = selected("contactNormalVelocity" + suffix, side, block, ...
        "vn", "SenseNormalVelocity", ...
        "Contact-point relative-velocity z component.", "m/s", ...
        "resolved in the block contact frame", ...
        "preserve the block-native +z component without inversion", "scalar", ownership); %#ok<AGROW>
    signals(end + 1) = selected("contactTangentialVelocity" + suffix, side, block, ...
        "vt", "SenseTangentialVelocity", ...
        "Contact-point relative tangential-velocity x/y components.", "m/s", ...
        "two components resolved in the block contact frame", ...
        "preserve block-native [+x;+y] components without inversion", "2-vector", ownership); %#ok<AGROW>
end
end

function item = emptySelected()
item = struct("name", "", "side", "", "sourceBlock", "", ...
    "sourcePort", "", "sensingParameter", "", "physicalMeaning", "", ...
    "unit", "", "frame", "", "sign", "", "sampleTime", "", ...
    "shape", "", "sideOwnership", "", "sourceClass", "", ...
    "observationOnly", false, "loggingName", "");
end

function item = selected(name, side, block, port, parameter, meaning, unit, ...
        frame, signRule, shape, ownership)
item = emptySelected();
item.name = name;
item.side = side;
item.sourceBlock = block;
item.sourcePort = port;
item.sensingParameter = parameter;
item.physicalMeaning = meaning;
item.unit = unit;
item.frame = frame;
item.sign = signRule;
item.sampleTime = ...
    "continuous Simscape physical signal; retain native timestamps";
item.shape = shape;
item.sideOwnership = ownership;
item.sourceClass = "plant_ground_truth";
item.observationOnly = true;
item.loggingName = name;
end

function signals = unavailableSignals(leftBlock, rightBlock)
blocks = [leftBlock, rightBlock];
signals = [ ...
    unavailable("normalCompressionInternalState", blocks, ...
        "No distinct compression-state sensing parameter exists; use the audited pen output only."), ...
    unavailable("contactPatchInternalState", blocks, ...
        "No contact-patch state sensing parameter or output port exists."), ...
    unavailable("vectorNormalForceR2024b", blocks, ...
        "Installed R2024b blocks expose SenseNormalForceMagnitude but no vector-normal-force sensing parameter."), ...
    unavailable("vectorFrictionForceR2024b", blocks, ...
        "Installed R2024b blocks expose SenseFrictionalForceMagnitude but no vector-friction-force sensing parameter."), ...
    unavailable("worldResolvedContactPoint", blocks, ...
        "Only base/follower-relative contact-frame translations are exposed; no audited world-resolved output is present.")];
end

function item = unavailable(name, blocks, blocker)
item = struct("name", name, "availability", "unavailable", ...
    "inspectedBlocks", blocks, "blocker", blocker, ...
    "maySubstituteProxy", false);
end

function signals = proxySignals()
signals = [ ...
    proxy("normalLoadDifference", "controller_proxy", ...
        "run_differential_identification: (QP right normal load - QP left normal load)/2"), ...
    proxy("contactForceLeftRight", "controller_proxy", ...
        "coupledQpSignal columns 33:38: feasible WBC/QP contact-force solution"), ...
    proxy("rollingResidual", "controller_proxy", ...
        "coupledQpSignal column 49: analytic WBC rolling residual"), ...
    proxy("wheelAngularQuantities", "derived_kinematic_proxy", ...
        "base pitch rate plus relative joint rates"), ...
    proxy("wheelPeripheralQuantities", "derived_kinematic_proxy", ...
        "wheel radius times derived wheel angular rate"), ...
    proxy("wheelCenterTangentQuantities", "derived_kinematic_proxy", ...
        "body forward velocity plus dxi")];
end

function item = proxy(name, sourceClass, provenance)
item = struct("name", name, "sourceClass", sourceClass, ...
    "provenance", provenance, "allowedRole", "diagnostic_only", ...
    "claimedPhysicalQuantity", "none", ...
    "mayServeAsContactPhysicalState", false);
end

function contract = observationLoggingContract(signals)
contract = struct();
contract.contractVersion = "06-01-G2-data-contract-v1";
contract.mode = "observation_only";
contract.requiredSelectedSignals = string({signals.name});
contract.requiredSides = ["left", "right"];
contract.missingSignalPolicy = "fail_closed";
contract.proxySubstitutionAllowed = false;
contract.wiringRule = ...
    "Enable the named sensing parameter and route its physical-signal port through a PS-Simulink Converter to logging only.";
contract.parameterInvariant = ["NormalForceType", "NormalStiffness", ...
    "NormalDamping", "NormalTransitionRegionWidth", "FrictionType", ...
    "CoefficientOfStaticFriction", "CoefficientOfDynamicFriction", ...
    "FrictionalCriticalVelocity"];
contract.geometryConnectionsInvariant = true;
contract.solverInvariant = true;
contract.requiredRawFields = string({signals.loggingName});
contract.requiredRawSupportFields = [ ...
    "baseNmpcState", "symmetryLegState", "coupledQpSignal", ...
    "nmpcBodyWrench", "totalUpperCommand"];
contract.requiredProcessedFields = [ ...
    "time", "xiDeltaLegacy", "dxiDeltaLegacy", ...
    "xiDeltaCanonical", "dxiDeltaCanonical", "vRollDelta", ...
    "uDiffRealizable", ...
    "contactStatusLeft", "contactStatusRight", ...
    "contactPenetrationLeft", "contactPenetrationRight", ...
    "contactPenetrationDelta", "contactPenetrationCommon", ...
    "contactNormalForceMagnitudeLeft", "contactNormalForceMagnitudeRight", ...
    "contactNormalForceMagnitudeDelta", "contactNormalForceMagnitudeCommon", ...
    "contactFrictionForceMagnitudeLeft", "contactFrictionForceMagnitudeRight", ...
    "contactFrictionForceMagnitudeDelta", "contactFrictionForceMagnitudeCommon", ...
    "contactNormalVelocityLeft", "contactNormalVelocityRight", ...
    "contactNormalVelocityDelta", "contactNormalVelocityCommon", ...
    "contactTangentialVelocityLeftX", "contactTangentialVelocityLeftY", ...
    "contactTangentialVelocityRightX", "contactTangentialVelocityRightY", ...
    "contactTangentialVelocityDeltaX", "contactTangentialVelocityDeltaY", ...
    "contactTangentialVelocityCommonX", "contactTangentialVelocityCommonY"];
contract.processedDefinitions = processedDefinitions();
contract.requiredManifestSnapshotFields = [ ...
    "schemaVersion", "status", "canonicalConvention", "legacyMapping", ...
    "selectedSignals", "unavailableSignals", "proxySignals", ...
    "sourceClasses", "loggingContract", "scopeFences", ...
    "escalation", "inspection"];
contract.timestampRequirements = struct( ...
    "raw", "preserve each source Time vector exactly", ...
    "rawValidity", "finite, strictly increasing, nonempty, and paired with every data sample", ...
    "processed", "use one explicit analysis time vector and record interpolation per field", ...
    "sampleTime", "record measured median diff(time); do not substitute controller or NMPC rate");
contract.unitRequirements = struct( ...
    "raw", "store the manifest-declared unit with every selected signal", ...
    "processed", "retain source unit through pair derivation", ...
    "converter", "PS-Simulink Converter output unit must equal selectedSignals.unit");
contract.failClosed = struct( ...
    "invalidStatus", "invalid_for_identification", ...
    "conditions", [ ...
        "missing selected left or right signal", ...
        "empty or nonfinite time/data", ...
        "nonmonotonic timestamp or time/data length mismatch", ...
        "unexpected scalar/vector shape", ...
        "unit or manifest schema mismatch"], ...
    "onFailure", "save raw/error metadata, omit approval eligibility, continue remaining cases", ...
    "allowProxyFallback", false);
contract.smoke = struct( ...
    "caseNames", ["Y_MS_y000_s01", "Y_MS_yp020_s01", "Y_MS_ym020_s01"], ...
    "yawRates", [0, 0.02, -0.02], ...
    "purpose", ["straight", "positive-yaw", "negative-yaw"], ...
    "agentMayRun", true, ...
    "outputRoot", "contact_state_discovery_smoke");
contract.manualFullBatch = struct( ...
    "entryPoint", "run_contact_state_discovery_batch", ...
    "mode", "full", ...
    "command", "run_contact_state_discovery_batch(""full"")", ...
    "caseCount", 25, ...
    "yawRates", [-0.04, -0.02, 0, 0.02, 0.04], ...
    "multisineSeeds", [101, 202, 303], ...
    "stepAmplitudes", [0.5, -0.5], ...
    "outputRoot", "contact_state_discovery_full", ...
    "resumeBehavior", ["skip-completed", "independent-case-save", ...
        "failure-continuation", "YawRate/Seed filters"], ...
    "expectedArtifacts", ["raw", "processed", "summary", ...
        "run_manifest", "analysis", "decision_evidence"], ...
    "owner", "human-manual-gate", ...
    "agentMayRun", false);
end

function definitions = processedDefinitions()
definitions = [ ...
    processed("xiDeltaLegacy", "(xiLeft-xiRight)/2", "rad", "legacy-v1"), ...
    processed("dxiDeltaLegacy", "(dxiLeft-dxiRight)/2", "rad/s", "legacy-v1"), ...
    processed("xiDeltaCanonical", "(xiRight-xiLeft)/2", "rad", "phase-6-canonical-v1"), ...
    processed("dxiDeltaCanonical", "(dxiRight-dxiLeft)/2", "rad/s", "phase-6-canonical-v1"), ...
    processed("vRollDelta", "(vRollRight-vRollLeft)/2", "m/s", "phase-6-canonical-v1"), ...
    processed("contact*Delta", "(contact*Right-contact*Left)/2", "source unit", "phase-6-canonical-v1"), ...
    processed("contact*Common", "(contact*Right+contact*Left)/2", "source unit", "phase-6-canonical-v1")];
end

function item = processed(name, definition, unit, schema)
item = struct("name", name, "definition", definition, ...
    "unit", unit, "schema", schema);
end

function fences = scopeFences()
fences = [ ...
    "No NMPC prediction-dynamics change", ...
    "No WBC objective, constraint, or controller change", ...
    "No plant or contact parameter change", ...
    "No terrain or contact switching change", ...
    "No solver, sample-time, limit, observer, or estimator change", ...
    "No independent TDelta, high-order ARX, neural model, or zContactSlow revival", ...
    "No full 25-case batch run by an agent"];
end

function value = escalation()
value = struct();
value.status = "ready_for_g2";
value.blockers = strings(0, 1);
value.requiredIf = [ ...
    "A selected source port, meaning, unit, frame, sign, or side cannot be reproduced", ...
    "Sensing or conversion changes contact equations, sample time, or solver behavior", ...
    "A proxy would be needed to replace a required plant-ground-truth signal"];
value.failureStatus = "requires_codex_decision";
end

function evidence = inspectionEvidence(leftBlock, rightBlock)
evidence = struct();
evidence.model = "model/simulate/two_legs/source.slx";
evidence.subsystem = "source/PD_only";
evidence.method = "MATLAB load_system/find_system/get_param/set_param audit; close_system(model,0)";
evidence.matlabRelease = "R2024b";
evidence.blocks = [ ...
    inspectedBlock(rightBlock, "right", ...
        "Cylindrical Solid", "Revolute Joint2"), ...
    inspectedBlock(leftBlock, "left", ...
        "Cylindrical Solid1", "Revolute Joint5")];
evidence.referenceBlock = "sm_lib/Forces and Torques/Spatial Contact Force";
evidence.normalModel = "SmoothSpringDamper";
evidence.frictionModel = "SmoothStickSlip";
evidence.baselineSensing = "all selected sensing parameters off; zero physical-signal outputs";
evidence.observationOnlyEvidence = ...
    "Toggling selected Sense* parameters adds physical-signal output ports while force-law parameters and B/F geometry connections remain unchanged; the model was closed without saving.";
evidence.documentation = ...
    "MathWorks Spatial Contact Force R2024b block reference, output-port definitions";
end

function item = inspectedBlock(path, side, wheelSolid, wheelJoint)
item = struct("path", path, "side", side, ...
    "baseGeometryConnection", wheelSolid, ...
    "wheelJointOwnership", wheelJoint, ...
    "followerGeometryConnection", "Brick Solid3 ground geometry", ...
    "baselineConservingPortCount", 2, ...
    "baselinePhysicalSignalOutputCount", 0);
end
