function y = coupled_two_leg_qp_signal(x)
%COUPLED_TWO_LEG_QP_SIGNAL Simulink adapter for the shared two-leg QP.
% Spatial layout: tau(6), wrench slack/feasible(12+12), slack norm,
% feasible flag, contact forces(3+3), exit flag, dynamics/contact/wrench
% residual norms, base qdd(6), directional contact residuals(3), common
% wheel error/solve time(3), differential torque(3), common wheel
% acceleration/command/residual(3), friction margins(4), torque margins(6),
% and differential wheel state/acceleration(4). Phase-07 diagnostics append
% canonical drift and the rank-1 stabilizer contract after legacy column 74.
% Phase-08 G2 diagnostics append uDiffRealizable projection scalars,
% projected wrench scalars, residual RMS, and controller-side/plant-status
% labels after column 85. Phase-08 task-attribution diagnostics append three
% 16-task vectors and two validity diagnostics after column 143. The
% default-off pairwise rolling/common-Fx hierarchy appends five diagnostics
% after column 193.

[tau, debug] = coupled_two_leg_qp_core(x);
y = [tau; debug.wrenchSlack; debug.wrenchFeasible; ...
    debug.wrenchSlackNorm; double(debug.qpFeasible); ...
    debug.FcLeft; debug.FcRight; debug.exitflag; ...
    norm(debug.dynamicsResidual, inf); ...
    norm(debug.contactAcceleration, 2); ...
    norm(debug.wrenchResidual, inf); debug.qddBase; ...
    debug.contactResidualDirection; debug.xiCommonError; ...
    debug.dxiCommonError; debug.qpSolveTime; debug.tauDifferential; ...
    debug.xiCommonAcceleration; debug.xiCommonCommand; ...
    abs(debug.xiCommonAcceleration - debug.xiCommonCommand); ...
    debug.frictionMargin; ...
    debug.torqueMargin; debug.xiDifferential; debug.dxiDifferential; ...
    debug.xiDifferentialAcceleration; debug.xiDifferentialCommand; ...
    debug.xiDeltaCanonical; debug.dxiDeltaCanonical; ...
    debug.uDiffCorrectionRequested; debug.uDiffCorrectionApplied; ...
    debug.uDiffNominal; debug.uDiffFinal; debug.uDiffRealized; ...
    double(debug.driftAmplitudeSaturated); ...
    double(debug.driftRateLimited); double(debug.driftFailSafe); ...
    double(debug.driftReset); ...
    debug.uDiffScalarRequested; debug.uDiffScalarApplied; ...
    debug.uDiffScalarFinal; debug.uDiffScalarQpFeasible; ...
    debug.uDiffProjectedRequested; debug.uDiffProjectedApplied; ...
    debug.uDiffProjectedFinal; debug.uDiffProjectedQpFeasible; ...
    debug.uDiffResidualRmsRequested; ...
    debug.uDiffResidualRmsApplied; debug.uDiffResidualRmsFinal; ...
    debug.uDiffResidualRmsQpFeasible; ...
    double(debug.qpFeasibleControllerSide); ...
    double(debug.plantWrenchUnavailable); ...
    debug.wbcTaskSensitivity; debug.wbcTaskCost; ...
    debug.wbcTaskResidual; double(debug.wbcTaskAttributionValid); ...
    debug.wbcTaskGradientClosure; ...
    double(debug.wbcRollingFxHierarchyRequested); ...
    double(debug.wbcRollingFxHierarchyApplied); ...
    double(debug.wbcRollingFxHierarchyStage1Feasible); ...
    debug.wbcRollingFxHierarchyStage1RollingAcceleration; ...
    debug.wbcRollingFxHierarchyLockResidual];
end
