function test_sagittal_task_intervention_contract()
%TEST_SAGITTAL_TASK_INTERVENTION_CONTRACT Verify one-variable audit cases.

projectDir = fileparts(fileparts(fileparts(fileparts(mfilename("fullpath")))));
resultRoot = fullfile(projectDir, "calibration", "results");
baselinePath = fullfile(resultRoot, ...
    "2026_08_normal_contact_diagnostic", "N0", ...
    "slope_terrain_timeseries", "slope_a100mrad_v020_raw.mat");
auditRoot = fullfile(resultRoot, "2026_08_sagittal_task_compatibility");
baseline = load(baselinePath, "ctrl", "wheelLqr", ...
    "trajectory", "slopeTerrain");

for variant = ["Roff", "Rtaskoff", "Foff", "Xoff", "Myoff"]
    candidate = load(fullfile(auditRoot, variant, ...
        "slope_terrain_timeseries", "slope_a100mrad_v020_raw.mat"), ...
        "ctrl", "wheelLqr", "trajectory", ...
        "slopeTerrain");
    assert(isequaln(candidate.wheelLqr, baseline.wheelLqr), ...
        "%s changed wheel planning.", variant);
    assert(isequaln(candidate.trajectory, baseline.trajectory), ...
        "%s changed the motion trajectory.", variant);
    assert(isequaln(candidate.slopeTerrain, baseline.slopeTerrain), ...
        "%s changed the terrain.", variant);

    normalized = candidate.ctrl;
    switch variant
        case "Roff"
            assert(~normalized.commonRollingSpeedTracker.enabled, ...
                "Roff did not disable the bundled rolling-speed subsystem.");
            normalized.commonRollingSpeedTracker.enabled = ...
                baseline.ctrl.commonRollingSpeedTracker.enabled;
        case "Rtaskoff"
            assert(normalized.commonRollingSpeedTracker.enabled ...
                && ~normalized.commonRollingSpeedTracker.taskEnabled, ...
                "Rtaskoff did not isolate the rolling-speed QP task.");
            normalized.commonRollingSpeedTracker = rmfield( ...
                normalized.commonRollingSpeedTracker, "taskEnabled");
        case "Foff"
            assert(~normalized.commonRollingSpeedTracker.forceFeedbackEnabled, ...
                "Foff did not disable rolling-force feedback correction.");
            normalized.commonRollingSpeedTracker.forceFeedbackEnabled = ...
                baseline.ctrl.commonRollingSpeedTracker.forceFeedbackEnabled;
        case "Xoff"
            assert(normalized.commonWheelPositionKp == 0 ...
                && normalized.commonWheelPositionKd == 0, ...
                "Xoff did not remove common wheel-position feedback.");
            assert(normalized.paperWheelAccelerationFeedforwardEnabled, ...
                "Xoff disabled the required wheel-acceleration feedforward.");
            normalized.commonWheelPositionKp = ...
                baseline.ctrl.commonWheelPositionKp;
            normalized.commonWheelPositionKd = ...
                baseline.ctrl.commonWheelPositionKd;
        case "Myoff"
            baselineWeight = baseline.ctrl.spatialQpWrenchPenalty ...
                /baseline.ctrl.spatialQpCommonWrenchScale(5)^2;
            candidateWeight = normalized.spatialQpWrenchPenalty ...
                /normalized.spatialQpCommonWrenchScale(5)^2;
            assert(candidateWeight/baselineWeight <= 1.01e-12, ...
                "Myoff did not effectively remove common pitch-moment weight.");
            assert(normalized.spatialQpDifferentialWrenchScale(5) ...
                == baseline.ctrl.spatialQpDifferentialWrenchScale(5), ...
                "Myoff changed differential pitch-moment weight.");
            normalized.spatialQpCommonWrenchScale(5) = ...
                baseline.ctrl.spatialQpCommonWrenchScale(5);
    end
    assert(isequaln(normalized, baseline.ctrl), ...
        "%s changed controller fields outside its intervention.", variant);
end

disp("Sagittal task intervention contract checks passed.");
end
