function contract = wheel_interface_wrench_contract()
%WHEEL_INTERFACE_WRENCH_CONTRACT Frozen physical wheel-interface semantics.
% This observation contract records the only direct plant wrench accepted by
% Phase 09.  It does not change model parameters, topology, or actuation.

contract = struct();
contract.contractVersion = "09-01-G1";
contract.quantity = "wheel follower total wrench acting on leg/base";
contract.rawFrame = "BaseFrame";
contract.nativeTimestamp = "Simscape physical-signal timestamp";
contract.canonicalDifferential = "(right-left)/2";
contract.scalarPolarity = 1;
contract.left = side("left", "source/PD_only/Revolute Joint5");
contract.right = side("right", "source/PD_only/Revolute Joint2");
contract.controller = struct( ...
    "frame", "controller body axes", ...
    "physicalToController", [1, 0, 0; 0, 0, 1; 0, 1, 0], ...
    "rotation", "R_CJ=P*R_WB'*R_WJ", ...
    "componentOrder", ...
        "[left Fx;Fy;Fz;Mx;My;Mz;right Fx;Fy;Fz;Mx;My;Mz]", ...
    "forceUnit", "N", "torqueUnit", "Nm", ...
    "momentOrigin", "coincident wheel-center origin", ...
    "originShiftAllowed", false);
contract.projection = struct( ...
    "helper", "project_uDiffRealizable", ...
    "basisPolicy", "frozen non-unit uDiffRealizable basis", ...
    "normalization", "none", ...
    "plantSpecificBasisAllowed", false);
contract.escalationConditions = [ ...
    "actor/receiver semantics cannot be proven", ...
    "coincident wheel-center origin cannot be proven", ...
    "force or torque sensing changes model behavior", ...
    "observation requires a reference shift, topology edit, or model save"];
end

function value = side(name, jointPath)
value = struct( ...
    "side", name, "jointPath", jointPath, ...
    "actor", "wheel follower", "receiver", "leg/base", ...
    "compositeWrenchDir", "FollowerOnBase", ...
    "compositeWrenchFrame", "BaseFrame", ...
    "forceUnit", "N", "torqueUnit", "Nm", ...
    "momentOrigin", "coincident wheel-center origin");
end
