stm32_bridge:
  ros__parameters:
    serial_device: /dev/ttyAMA4
    baud_rate: 921600
    command_rate_hz: 200.0
    command_source_timeout_ms: 100
    frame_id: base_link
    joint_names:
      - left_hip
      - left_knee
      - left_wheel
      - right_hip
      - right_knee
      - right_wheel
